### ISSUE TITLE
Unable to apply double transforms to mustache-sequences

### ISSUE THREAD

**Issue by MahdiBM** [hummingbird-project/swift-mustache#35]
Here's a failing test to repro:

```swift
    func testDoubleSequenceTransformDoesNotWork() throws {
        let template = try MustacheTemplate(string: """
        {{#repo}}
        {{#reversed(numbers)}}{{count(.)}}{{/reversed(numbers)}}
        {{/repo}}

        """)
        let object: [String: Any] = ["repo": ["numbers": [1, 2, 3]]]
        XCTAssertEqual(template.render(object), """
        3

        """)
    }
```

**Comment by adam-fowler** [comment]
This is correct here. The `{{#reversed(numbers)}}...{{/reversed(numbers)}}` expands out into the individual elements so `count` is being applied to the individual elements. But it would be good to enable double transforms of the form
`{{#reversed(count(numbers))}}...{{/reversed(count(numbers))}}`

**Comment by MahdiBM** [comment]
yes please, that might be the best solution.

**Comment by MahdiBM** [comment]
> This is correct here

I'm not quite sure about it being "correct", but looking at the code, it does seem to be quite hard to fix.
So i'll be happy with what you proposed, since that's better anyway.

**Comment by MahdiBM** [comment]
@adam-fowler I implemented this. I'll propose the changes in a few days or a week or two when i'm done with my fork.
